- name: Generate region naming and tagging variables
  include_vars:
    file: region.yml

- name: Generate environment naming and tagging variables
  include_vars:
    file: environment.yml

- name: Generate division naming and tagging variables
  include_vars:
    file: division.yml

