smiths_config_metadata:
  divisions:
    bis:
      name: BIS
    flextek:
      name: Flex-Tek
    johncrane:
      name: John Crane
    detection:
      name: Smiths Detection
    group:
      name: Smiths Group
    interconnect:
      name: Smiths Interconnect
    medical:
      name: Smiths Medical
  environments:
    prd:
      name: Production
    npd:
      name: Non-Production
    shr:
      name: Shared
    dev:
      name: Development
  locations:
    zna1:
      name: North Central US
      type: Primary
      address_space: 10.216.0.0/17
      timezone: "-0600"
    zna2:
      name: South Central US
      type: DR
      address_space: 10.216.128.0/17
      timezone: "-0600"
    zna3:
      name: East US
      type: Primary
    zna4:
      name: West US
      type: DR
    zna5:
      name: East US 2
      type: Primary
    zna6:
      name: Central US
      type: DR
    zeu1:
      name: West Europe
      type: Primary
      address_space: 10.217.0.0/17
      timezone: "+0100"
    zeu2:
      name: North Europe
      type: DR
      address_space: 10.217.128.0/17
      timezone: "+0100"
  purposes:
    rd:
      name: R&D
  tags:
    networking:
      Service: Infrastructure
      Application: Networking
      Data Classification: Internal
      PII: "No"
      Owner Phone: +1 240-361-8382
      Schedule: 24 x 7
      SME E-mail: BIS Security Team
      Owner E-mail: mike.barker@smiths.com
      Department: IT
      PCI DSS: "No"
      Maintenance Windows: Cloud Native
    ad:
      Service: Infrastructure
      Application: Active Directory
      Data Classification: Smiths Confidential
      PII: "No"
      Owner Phone: +1 651-402-9368
      Schedule: 24 x 7
      SME E-mail: BIS AD Team
      Owner E-mail: john.rowan@smiths.com
      Department: IT
      PCI DSS: "No"
      Maintenance Windows: Standard
  api_versions:
    networking: "2018-08-01"
    insights: "2017-05-01-preview"
    storage: "2018-07-01"
    compute: "2018-10-01"
  images:
    Windows Server 2008 R2:
      publisher: MicrosoftWindowsServer
      offer: WindowsServer
      sku: 2008-R2-SP1
      version: latest
    Windows Server 2012 R2:
      publisher: MicrosoftWindowsServer
      offer: WindowsServer
      sku: 2012-R2-Datacenter
      version: latest
    Windows Server 2016:
      publisher: MicrosoftWindowsServer
      offer: WindowsServer
      sku: 2016-Datacenter
      version: latest
    Windows Server 2019:
      publisher: MicrosoftWindowsServer
      offer: WindowsServer
      sku: 2019-Datacenter
      version: latest
